
#Connection string: jdbc:mysql://localhost:15432/postgres
version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "clinic_db"
    ports:
      - "15432:5432"
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d

